# Generated by Django 5.0.4 on 2024-05-13 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organizer', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description provided')),
                ('prize', models.CharField(max_length=50)),
                ('registration_open', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competition_logos/')),
                ('competition_type', models.CharField(choices=[('League', 'League'), ('Cup', 'Cup')], default='League', max_length=10)),
                ('is_group_stage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='player_image/')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('CB', 'Center Back'), ('FB', 'Full Back'), ('WB', 'Wing Back'), ('CM', 'Midfielder'), ('DM', 'Defensive Midfielder'), ('CM', 'Center Midfielder'), ('AM', 'Attacking Midfielder'), ('WG', 'Winger'), ('FW', 'Forward'), ('CF', 'Centre Forward'), ('ST', 'Striker'), ('UT', 'Utility Player')], max_length=2)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_games', models.IntegerField(default=0)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('foot', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], default='Right', max_length=10)),
                ('biography', models.TextField(blank=True, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='player_post_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='competition_management.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, default='default/soccer.png', null=True, upload_to='team_logos/')),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_coached', to='competition_management.coach')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='competition_management.team'),
        ),
        migrations.CreateModel(
            name='CupGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('competition', models.ForeignKey(limit_choices_to={'competition_type': 'Cup'}, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competition_management.competition')),
                ('teams', models.ManyToManyField(related_name='groups', to='competition_management.team')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='competition_management.team'),
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.CharField(default='N/A', max_length=2)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='competition_management.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competition_management.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='competition_management.team')),
            ],
            options={
                'unique_together': {('player', 'competition', 'team')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'team')},
        ),
    ]
