# Generated by Django 5.0.4 on 2024-05-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
