# Generated by Django 5.0.4 on 2024-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0002_team_location_alter_competition_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default='N/A', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('CB', 'Center Back'), ('FB', 'Full Back'), ('WB', 'Wing Back'), ('CM', 'Midfielder'), ('DM', 'Defensive Midfielder'), ('CM', 'Center Midfielder'), ('AM', 'Attacking Midfielder'), ('WG', 'Winger'), ('FW', 'Forward'), ('CF', 'Centre Forward'), ('ST', 'Striker'), ('UT', 'Utility Player')], default='N/A', max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default='N/A', max_digits=5, null=True),
        ),
    ]
