# Generated by Django 5.0.4 on 2024-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0005_alter_player_height_alter_player_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
