# Generated by Django 5.0.4 on 2024-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0006_alter_competition_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
