# Generated by Django 5.0.4 on 2024-05-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0009_remove_competition_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerregistration',
            name='player_number',
        ),
    ]
