# Generated by Django 5.0.4 on 2024-05-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0010_remove_playerregistration_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
