# Generated by Django 5.0.4 on 2024-05-30 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0014_playercomment_playerlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(choices=[('Round of 16', 'Round of 16'), ('Quarterfinals', 'Quarterfinals'), ('Semifinals', 'Semifinals'), ('Final', 'Final')], max_length=50)),
                ('match_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_away_matches', to='competition_management.team')),
                ('competition', models.ForeignKey(limit_choices_to={'competition_type': 'Cup'}, on_delete=django.db.models.deletion.CASCADE, related_name='knockout_matches', to='competition_management.competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_home_matches', to='competition_management.team')),
            ],
        ),
    ]
