# Generated by Django 5.0.4 on 2024-05-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0016_delete_knockoutmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupKnockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(choices=[('Round of 16', 'Round of 16'), ('Quarterfinals', 'Quarterfinals'), ('Semifinals', 'Semifinals'), ('Final', 'Final')], max_length=50)),
                ('competition', models.ForeignKey(limit_choices_to={'competition_type': 'Cup'}, on_delete=django.db.models.deletion.CASCADE, related_name='knockouts', to='competition_management.competition')),
                ('teams', models.ManyToManyField(related_name='knockouts', to='competition_management.team')),
            ],
        ),
    ]
