# Generated by Django 5.0.4 on 2024-05-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0017_cupknockout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CupKnockout',
        ),
    ]
