# Generated by Django 5.0.4 on 2024-09-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0022_competition_is_school_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='name',
        ),
        migrations.AddField(
            model_name='coach',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TeamCoachCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('date_assigned', models.DateField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition_management.coach')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition_management.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition_management.team')),
            ],
        ),
    ]
