# Generated by Django 5.0.4 on 2024-09-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_vote_confirmation_token_vote_confirmation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='category',
        ),
    ]
