# Generated by Django 5.0.4 on 2024-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_remove_vote_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
