# Generated by Django 5.0.4 on 2024-09-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_awardcategory_coaches_vote_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardcategory',
            name='category',
            field=models.CharField(choices=[('most_valuable_player', 'MVP'), ('man_of_the_match', 'Man of the Match'), ('best_player', 'Best Player'), ('top_scorer', 'Top Scorer'), ('best_goalkeeper', 'Best Goalkeeper'), ('best_team', 'Best Team'), ('best_coach', 'Best Coach')], max_length=50),
        ),
    ]
