# Generated by Django 5.0.4 on 2024-10-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_alter_awardcategory_category'),
    ]

    operations = [
    ]
