# Generated by Django 5.0.4 on 2024-10-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20241012_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardcategory',
            old_name='nominees',
            new_name='players',
        ),
    ]
