# Generated by Django 5.0.4 on 2024-05-13 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('feedback_type', models.CharField(choices=[('website', 'Website Navigation'), ('content', 'Content Quality'), ('feature', 'Feature Request'), ('bug', 'Bug Report')], default='website', max_length=100)),
                ('experience_rating', models.IntegerField(default=0)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoccerNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('news_url', models.URLField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('published_date', models.DateTimeField()),
                ('news_type', models.CharField(choices=[('HOT', 'Hot'), ('TRENDING', 'Trending')], default='HOT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_awarded', models.DateField()),
                ('category', models.CharField(choices=[('Player', 'Player'), ('Coach', 'Coach'), ('Referee', 'Referee'), ('Team', 'Team')], max_length=10)),
                ('player_award', models.CharField(blank=True, choices=[('Man of the Match', 'Man of the Match'), ('Best Goalkeeper', 'Best Goalkeeper'), ('Best Player', 'Best Player'), ('Top Scorer', 'Top Scorer'), ('Top Assist', 'Top Assist')], max_length=20, null=True)),
                ('coach_award', models.CharField(blank=True, choices=[('Best Coach', 'Best Coach')], max_length=20, null=True)),
                ('referee_award', models.CharField(blank=True, choices=[('Best Referee', 'Best Referee')], max_length=20, null=True)),
                ('team_award', models.CharField(blank=True, choices=[('Best Team', 'Best Team'), ('Fair Play', 'Fair Play')], max_length=20, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='competition_management.coach')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='competition_management.competition')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='competition_management.player')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='competition_management.referee')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='competition_management.team')),
            ],
        ),
    ]
