# Generated by Django 5.0.4 on 2024-09-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_awardcategory_close_date_awardcategory_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
