# Generated by Django 5.0.4 on 2024-09-07 07:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_vote_confirmation_token_vote_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
