# Generated by Django 5.0.4 on 2024-09-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_vote_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='confirmation_token',
        ),
        migrations.AddField(
            model_name='vote',
            name='confirmation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
