# Generated by Django 5.0.4 on 2024-10-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_alter_awardcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardcategory',
            name='hide_vote_count',
            field=models.BooleanField(default=False),
        ),
    ]
