# Generated by Django 5.0.4 on 2024-08-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_management', '0002_remove_penaltyshootout_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penaltyshootout',
            old_name='is_shootout',
            new_name='is_scored',
        ),
        migrations.AddField(
            model_name='result',
            name='is_shootout',
            field=models.BooleanField(default=False),
        ),
    ]
