# Generated by Django 5.0.4 on 2024-08-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_management', '0004_remove_result_is_shootout'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyshootout',
            name='is_shootout',
            field=models.BooleanField(default=False),
        ),
    ]
