# Generated by Django 5.0.4 on 2024-08-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_management', '0005_penaltyshootout_is_shootout'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_penalty',
            field=models.BooleanField(default=False),
        ),
    ]
