# Generated by Django 5.0.4 on 2024-09-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_management', '0007_alter_match_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_second_yellow',
            field=models.BooleanField(default=False),
        ),
    ]
