# Generated by Django 5.0.4 on 2024-09-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_management', '0024_coach_picture'),
        ('match_management', '0008_card_is_second_yellow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='man_of_the_match',
        ),
        migrations.AddField(
            model_name='result',
            name='man_of_the_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition_management.player'),
        ),
    ]
