# Generated by Django 5.0.4 on 2024-10-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_management', '0010_matchcomment_matchlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_penalty',
        ),
    ]
